#!/bin/bash

NODE_EXPORTER_VER=0.18.1
curl -LO https://github.com/prometheus/node_exporter/releases/download/v$NODE_EXPORTER_VER/node_exporter-$NODE_EXPORTER_VER.linux-armv7.tar.gz

tar xvf node_exporter-$NODE_EXPORTER_VER.linux-armv7.tar.gz

mv node_exporter-$NODE_EXPORTER_VER.linux-armv7/node_exporter /usr/local/bin/node_exporter

useradd -m -s /bin/bash node_exporter

cat << EOF >> /etc/systemd/system/node_exporter.service

[Unit]
Description=Node Exporter
Wants=network-online.target
After=network-online.target

[Service]
User=node_exporter
Group=node_exporter
Type=simple
ExecStart=/usr/local/bin/node_exporter
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable node_exporter
systemctl start node_exporter
systemctl status node_exporter



